src/config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.urls import re_path
from django.views import defaults as default_views
from django.views.generic import TemplateView, RedirectView

urlpatterns = (
        [
            path("i18n/", include("django.conf.urls.i18n")),
            path(settings.ADMIN_URL + 'doc/', include('django.contrib.admindocs.urls')),
            path("employees/", include("project.employees.urls")),
        ]
        + i18n_patterns(path(settings.ADMIN_URL, admin.site.urls))
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

# API URLS
# ------------------------------------------------------------------------------
urlpatterns += []

# django-hijack
# ------------------------------------------------------------------------------
# https://django-hijack.readthedocs.io/en/stable/
urlpatterns += [path('hijack/', include('hijack.urls'))]

# DEBUG
# ------------------------------------------------------------------------------
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += []

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

    if "rosetta" in settings.INSTALLED_APPS:
        urlpatterns += [re_path(r"^rosetta/", include("rosetta.urls"))]

src/project/employees/urls.py
from django.urls import path
from .views import EmployeeListView, EmployeeCreateView

app_name = 'employees'

urlpatterns = [
    path('', EmployeeListView.as_view(), name='employees_list'),
    path('create/', EmployeeCreateView.as_view(), name='employee_create'),
]

src/project/employees/models.py
from django.db.models import (PROTECT, CharField, ForeignKey, ManyToManyField,
                              SmallIntegerField, TextField)
from django.utils.translation import gettext_lazy as _

from project.utils.models import BaseModel


class SpecialistTypes(BaseModel):
    name = CharField(_("Specialist type name"), max_length=255)
    description = TextField(_("Specialist type description"), default="")

    class Meta:
        db_table = "specialist_types"
        db_table_comment = "Table include data of all specialist types"

        get_latest_by = "update"
        ordering = ("update", "name")

        verbose_name = _("Specialist type")
        verbose_name_plural = _("Specialist types")

    def __str__(self):
        return self.name

class WorkingDays(BaseModel):
    order = SmallIntegerField(_("Working days order"))
    name = CharField(_("Working day name"), max_length=255)
    shortened_name = CharField(_("Shortened name"), max_length=255, default="")

    class Meta:
        db_table = "working_days"
        db_table_comment = "Table include data of working days"

        get_latest_by = "order"
        ordering = ("order",)

        verbose_name = _("Working day")
        verbose_name_plural = _("Working days")

    def __str__(self):
        return self.name

class Employees(BaseModel):
    user = ForeignKey("auth.User", related_name="employees", on_delete=PROTECT)
    specialist_type = ForeignKey(SpecialistTypes, on_delete=PROTECT, verbose_name=_("Specialist type"))
    working_days = ManyToManyField(WorkingDays, verbose_name=_("Working days"), blank=True)

    class Meta:
        db_table = "employees"
        db_table_comment = "Table include data of all employees"

        get_latest_by = "update"
        ordering = ("update", "user")

        verbose_name = _("Employee")
        verbose_name_plural = _("Employees")

    def __str__(self):
        return "{type} {full_name}".format(type=self.specialist_type.name, full_name=self.user.get_full_name())

    def get_working_days(self):
        return [day.shortened_name for day in self.working_days.all()]

    def working_schedule(self):
        working_days = self.working_days.all()
        working_schedules = self.visits_set.all()

        result = {
            day: [
                workings.time_visit.all().filter(date=day)
                for workings in working_schedules
            ]
            for day in working_days
        }

        return result

src/project/utils/models/models.py
from django.db.models import DateTimeField, Model
from django.utils.translation import gettext as _


class BaseModel(Model):
    create = DateTimeField(
        _("Create time"), help_text=_("Timestamp of object create"), blank=True, auto_now_add=True
    )
    update = DateTimeField(
        _("Update time"), help_text=_("Timestamp of object update"), blank=True, auto_now=True
    )

    class Meta:
        abstract = True

src/project/visitors/models.py
from django.db.models import (BooleanField, CharField, DateField, EmailField,
                              ManyToManyField, TextField)
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

from project.utils.models import BaseModel

from .managers import ChildManager, ParentManager


class Visitor(BaseModel):
    fio = CharField(_("Full name visitor"), max_length=500)
    phone_number = PhoneNumberField(verbose_name=_("Phone number"), blank=True)
    mail = EmailField(_("Mail"), blank=True)
    address = CharField(_("Address"), max_length=500, blank=True)
    is_child = BooleanField(_("Is children?"), default=False)
    parent_problem = TextField(_("Parent problem"), blank=True)

    children = ManyToManyField("visitors.Visitor", verbose_name=_("Children"), related_name="child", blank=True)
    birth_data = DateField(_("Birth date"), null=True, blank=True)

    reason_for_request = TextField(_("Reason for request"), default="", blank=True)

    class Meta:
        db_table = "visitors"
        db_table_comment = "Table include data of all visitors"

        get_latest_by = "update"
        ordering = ("update", "fio")

        verbose_name = _("Visitor")
        verbose_name_plural = _("Visitors")

    def __str__(self) -> str:
        if self.is_child:
            return "{full_name}".format(full_name=self.fio)
        return "{is_child} - {phone_number}:{full_name} - {count_children} children".format(
            is_child=_("Child") if self.is_child else _("Parent"),
            phone_number=self.phone_number,
            full_name=self.fio,
            count_children=self.children.count(),
        )

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None, *args, **kwargs) -> None:
        super().save(force_insert, force_update, using, update_fields)


class Parent(Visitor):
    objects = ParentManager()
    class Meta:
        proxy = True

class Child(Visitor):
    objects = ChildManager()
    class Meta:
        proxy = True

src/project/visits/models.py
from django.db.models import (PROTECT, CharField, DateTimeField, ForeignKey,
                              PositiveSmallIntegerField, SlugField, TextField, TimeField, ManyToManyField)
from django.utils.translation import gettext_lazy as _
from model_utils import Choices

from datetime import datetime, timedelta

from project.utils.models import BaseModel
from project.utils.slugify import slugify


class TimeVisits(BaseModel):
    date = ForeignKey("employees.WorkingDays", on_delete=PROTECT, verbose_name=_("Date of visit"))
    time = TimeField(_("Time of visit"))

    def __str__(self):
        return "{day} - {time}".format(day=self.date.shortened_name, time=self.time.strftime("%H:%M"))


class TypeVisit(BaseModel):
    name = CharField(_("Type name"), max_length=255)
    description = TextField(_("Description"))

    slug = SlugField()

    class Meta:
        db_table = "type_visit"
        db_table_comment = "Table include data of all type of visits"

        get_latest_by = "create"
        ordering = ("create",)

        verbose_name = _("Type visit")
        verbose_name_plural = _("Visits types")

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, *args, **kwargs) -> None:
        self.slug = slugify(self.name)
        super().save(force_insert=False, force_update=False, *args, **kwargs)


class Session(BaseModel):
    name = CharField(_("Session name"), max_length=255)
    description = TextField(_("Session description"))

    slug = SlugField(unique=True)

    class Meta:
        db_table = "visit_sessions"
        db_table_comment = "Table include data of all visits session"

        get_latest_by = "create"
        ordering = ("create",)

        verbose_name = _("Visit session")
        verbose_name_plural = _("Visits sessions")

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, *args, **kwargs) -> None:
        self.slug = slugify(self.name)
        super().save(force_insert=False, force_update=False, *args, **kwargs)


class CompletedSession(BaseModel):
    STATUS = Choices(
        ("held", _("Held")),
        ("not_held", _("Not held"))
    )

    status = CharField(_("Session status"), choices=STATUS, default=STATUS.not_held, max_length=255)
    reason = TextField(_("Session reason"))

    class Meta:
        db_table = "completed_session"
        db_table_comment = "Table include data of all completed sessions"

        get_latest_by = "update"
        ordering = ("update",)

        verbose_name = _("Completed session")
        verbose_name_plural = _("Completed sessions")


class Visits(BaseModel):
    status = Choices(
        ("active", _("Active")),
        ("inactive", _("Inactive")),
    )

    child = ForeignKey("visitors.Child", on_delete=PROTECT, verbose_name=_("Child"))
    accountable = ForeignKey("employees.Employees", on_delete=PROTECT, verbose_name=_("Accountable"))

    time_visit = ManyToManyField(TimeVisits, verbose_name=_("Visits time"))
    type_visit = ForeignKey(TypeVisit, on_delete=PROTECT, verbose_name=_("Visit type"))
    session = ForeignKey(Session, on_delete=PROTECT, verbose_name=_("Session"))
    visits_count = PositiveSmallIntegerField(_("Visits count"), default=1)

    completed_sessions = ManyToManyField(CompletedSession, verbose_name=_("Completed sessions"), blank=True)

    class Meta:
        db_table = "visits"
        db_table_comment = "Table include data of all visits"

        get_latest_by = "update"
        ordering = ("update",)

        verbose_name = _("Visit")
        verbose_name_plural = _("Visits")

    #TODO дописать __str__

src/project/employees/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm

from .models import Employees, WorkingDays
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model, password_validation
from project.utils.slugify import slugify
from django.utils.translation import gettext_lazy as _
User = get_user_model()


class EmployeeForm(forms.ModelForm):
    user_first_name = forms.CharField(label=_("First Name"), widget=forms.TextInput(attrs={"placeholder": "First Name"}))
    user_last_name = forms.CharField(label=_("Last Name"), widget=forms.TextInput(attrs={"placeholder": "Last name"}))
    user_password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    user_email = forms.EmailField()
    user_group = forms.ModelChoiceField(queryset=Group.objects.all())

    class Meta:
        model = Employees
        fields = [
            "user_first_name",
            "user_last_name",
            "user_password",
            "user_email",
            "user_group",
            "specialist_type",
            "working_days"
        ]
        widgets = {
            "working_days": forms.CheckboxSelectMultiple
        }

    def _post_clean(self):
        super()._post_clean()

        password = self.cleaned_data.get("user_password")

        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except ValidationError as error:
                self.add_error("user_password", error)

    def save(self, commit=True):
        instance = super().save(commit=False)

        if commit:
            user = User.objects.create_user(
                username=slugify("{last_name}_{first_name}".format(
                    last_name=self.cleaned_data["user_last_name"],
                    first_name=self.cleaned_data["user_first_name"],
                )),
                first_name=self.cleaned_data["user_first_name"],
                last_name=self.cleaned_data["user_last_name"],
                email=self.cleaned_data["user_email"],
                password=self.cleaned_data["user_password"],
            )
            user.groups.add(self.cleaned_data["user_group"])

            instance.user = user
            instance.save()

            if hasattr(self, "save_m2m"):
                self.save_m2m()

        return instance

src/project/utils/forms/fields.py
from django.forms import ClearableFileInput, DateInput, FileField


class MultipleFileInput(ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class CustomDateInput(DateInput):
    input_type = 'date'

src/project/visitors/forms.py
from django import forms
from phonenumber_field.formfields import SplitPhoneNumberField

from .models import Visitor


class VisitorForm(forms.ModelForm):
    phone_number = SplitPhoneNumberField(initial="RU", required=False)
    class Meta:
        model = Visitor
        fields = ("fio", "phone_number", "mail", "address", "is_child", "children", "reason_for_request")

src/project/visits/forms.py
from django import forms
from .models import TimeVisits


class TimeVisitsForm(forms.ModelForm):
    time = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))
    class Meta:
        model = TimeVisits
        fields = ("date", "time")

src/project/employees/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from project.utils.mixins.premissions import CustomGroupRequiredMixin
from .models import Employees, WorkingDays
from .forms import EmployeeForm

class EmployeeListView(CustomGroupRequiredMixin, ListView):
    required_groups = ["Сотрудник"]

    template_name = "employees/employees_list_view.html"
    model = Employees

    def get_queryset(self):
        self.queryset = (
            Employees.objects.all()
            .select_related("user", "specialist_type")
            .prefetch_related("working_days", "visits_set")
        )
        return super().get_queryset()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        context["working_days"] = WorkingDays.objects.all()

        return context


class EmployeeCreateView(CustomGroupRequiredMixin, CreateView):
    required_groups = ["Директор"]

    template_name = "employees/employees_create_view.html"
    model = Employees

    form_class = EmployeeForm

    success_url = reverse_lazy("employees:employees_list")

src/project/visits/views.py
# Create your views here.

src/project/templates/base.html
{% load static i18n %}

<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}

<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>

    <title>
        {% block title %}Tempalte for Django project{% endblock title %}
    </title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <meta name="description"
          content="Project!"/>

    <meta name="author"
          content="Poletaev Alexandr Kirillovich"/>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/favicon/site.webmanifest' %}">

    {% block css %}
        <!-- Latest compiled and minified Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
              crossorigin="anonymous">

        <!-- Your stuff: Third-party CSS libraries go here -->
        <link href="{% static 'css/modules/jquery.datetimepicker.css' %}" rel="stylesheet"/>

        <!-- Bootstrap Icons -->
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

        <link rel="stylesheet" href="{% static 'js/modules/pdf-viewer/css/pdfviewer.jquery.css' %}">

        <!-- This file stores project-specific CSS -->
        <link href="{% static 'css/project.css' %}" rel="stylesheet"/>
    {% endblock css %}

    {% block page_css %}
    {% endblock %}
    <!-- Le javascript
        ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
        <!-- Jquery -->
        <script src="{% static 'js/modules/jquery-3.7.1.js' %}"></script>

        <!-- jquery-datetimepicker -->
        <script src="{% static 'js/modules/jquery.datetimepicker.full.min.js' %}"></script>

        <script src="{% static 'js/modules/moment-with-locales.js' %}"></script>

        <!-- Bootstrap JS -->
        <script src="{% static 'js/modules/popper/popper.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
                integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
                crossorigin="anonymous"></script>

        <!-- Axios -->
        <script src="{% static 'js/modules/axios.js' %}"></script>

        <!-- SweetAlert2 -->
        <script src="{% static 'js/modules/sweetalert2@11.js' %}"></script>

        <!-- fullcalendar -->
        <script src={% static 'js/modules/fullcalendar@6_1_11/index.global.min.js' %}></script>
        <script src={% static 'js/modules/fullcalendar@6_1_11/locales-all.global.min.js' %}></script>

        <!-- Gauntface Logger -->
        <script src="{% static 'js/modules/gauntface/logger/browser-globals.js' %}"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js"></script>
        <script src="{% static 'js/modules/pdf-viewer/js/pdfviewer.jquery.js' %}"></script>

        <!-- Your stuff: Third-party javascript libraries go here -->
        <!-- place project specific Javascript in this file -->
        <script defer src="{% static 'js/project.js' %}"></script>
        <script defer src="{% static 'js/dal_init_funcs.js' %}"></script>
        <script defer src="{% static 'js/i18n.js' %}"></script>
    {% endblock javascript %}
</head>
<body>
<div class="mb-1">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand ms-4" href="#">Речевой центр "Все звуки"</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse m-2" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="ms-2 nav-item navbar-item">
                        <a class="nav-link active" aria-current="page"
                           href="#">{% translate "Homepage" %}</a>
                    </li>
                
                    {% if request.user.is_authenticated %}
                        <li class="ms-2 nav-item navbar-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                <i class="bi bi-person-lines-fill pe-2"></i>
                                <span>{% translate "Employees" %}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" href="{% url 'employees:employees_list' %}">
                                        <span>{% translate "Employees list" %}</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'employees:employee_create' %}">
                                        <span>{% translate "Hire employee" %}</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>

<div id="back-ground" class="m-5 p-5 shadow-box">
    <div class="container-fluid">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                    {{ message }}
                    <button type="button"
                            class="btn-close"
                            data-bs-dismiss="alert"
                            aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}

        {% if form.errors %}
            <div class="alert alert-error">
                <h4>Please fix the following errors</h4>
                <ul>
                    {% for field in form %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </ul>
                {% if form.non_field_errors %}
                    {{ form.non_field_errors }}
                {% endif %}
            </div>
        {% endif %}

        {% block content %}
        {% endblock content %}

        {% block pagination %}
        {% endblock pagination %}
    </div>
</div>

{% block modal %}
{% endblock modal %}

{% block inline_javascript %}
    {% comment %}
        Script tags with only code, no src (defer by default). To run
        with a "defer" so that you run inline code:
        <script>
            window.addEventListener('DOMContentLoaded', () => {
                /* Run whatever you want */
            });
        </script>
    {% endcomment %}
{% endblock inline_javascript %}

</body>
</html>